# Limpando Base de Dados Simples

#### Esta base de dados é referente a clientes de um banco e sua situação de pagamento ou não pagamento de um empréstimo

## Importando bibliotecas e base de dados

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
base = pd.read_excel('ChavesClientes.xlsx')
base.head()

   ID ChaveSituacao ClassRisco   CatCliente  Pagamento
0   1          32FC     Ccinza  Basic-Alpha          1
1   2          25MV   AAmarelo        Black          1
2   3          27MV  B-Amarelo   Basic-Beta          1
3   4          26FD   BAmarelo        Black          0
4   5          26FD  C-Amarelo        Black          0

#### As colunas da base da dados parecem confusas no início, porém sua explicação é simples:
- A coluna "ChaveSituação" diz respeito a:
 * idade: 2 primeiros números 
 * sexo: M (masculino), F (feminino)
 * estado civil: S (solteiro), C (casado), D (divorciado), V (viuvo)
- A coluna "ClassRisco":
 * Classifica o cliente como A,B ou C e o indicador + ou -.
 * Cor do cliente de acordo com um modelo de churn interno da empresa ()
- A coluna "CatCliente" é formada por:
 * Categoria do cartão (Basic, Black, Platinum)
 * Categoria VIP (Alpha, Beta)
 
 Vamos começar simplesmente separando as colunas em colunas individuais

## Separando as colunas

In [34]:
#Separando a ChaveSituacao
base['Idade'] = base.ChaveSituacao.apply(lambda string: string[:2])
base['Sexo'] = base.ChaveSituacao.apply(lambda string: string[2:3])
base['EstadoCivil'] = base.ChaveSituacao.apply(lambda string: string[-1])

#Separando a CatCliente
base['Categoria'] = base.CatCliente.str.split('-').str.get(0)
base['Cliente'] = base.CatCliente.str.split('-').str.get(1)

#Separando ClassRisco
base['Classe'] = base.ClassRisco.str[0]

def indicador(string):
    if '-' in string: return '-'
    elif '+' in string: return '+'
    else: return np.nan
    
base['Indicador'] = base.ClassRisco.apply(indicador)

def risco(risco):
    if 'cinza' in risco.lower(): return "cinza"
    elif 'amarelo' in risco.lower(): return 'amarelo'
    elif 'verde' in risco.lower(): return 'verde'
    elif 'roxo' in risco.lower(): return 'roxo'
    else: return np.nan
    
base['Risco'] = base.ClassRisco.apply(risco)

#Converteremos a coluna idade para o formato numérico, pois agora ela está como objeto

base['Idade'] = pd.to_numeric(base['Idade'])

In [42]:
base

,ID,ChaveSituacao,ClassRisco,CatCliente,Pagamento,Idade,Sexo,EstadoCivil,Categoria,Cliente,Classe,Indicador,Risco
0,1,32FC,Ccinza,Basic-Alpha,1,32,F,C,Basic,Alpha,C,NaN,cinza
1,2,25MV,AAmarelo,Black,1,25,M,V,Black,Comum,A,NaN,amarelo
2,3,27MV,B-Amarelo,Basic-Beta,1,27,M,V,Basic,Beta,B,-,amarelo
3,4,26FD,BAmarelo,Black,0,26,F,D,Black,Comum,B,NaN,amarelo
4,5,26FD,C-Amarelo,Black,0,26,F,D,Black,Comum,C,-,amarelo
5,6,28FC,C-Amarelo,Platinum-Alpha,0,28,F,C,Platinum,Alpha,C,-,amarelo
6,7,27MD,A-Verde,Platinum-Beta,1,27,M,D,Platinum,Beta,A,-,verde
7,8,31MD,C-Cinza,Basic,0,31,M,D,Basic,Comum,C,-,cinza
8,9,28FS,A-Cinza,Black,1,28,F,S,Black,Comum,A,-,cinza
9,10,31MV,C+Amarelo,Platinum,1,31,M,V,Platinum,Comum,C,+,amarelo
10,11,29MV,AAmarelo,Basic,1,29,M,V,Basic,Comum,A,NaN,amarelo
11,12,30FC,C-Cinza,Basic-Beta,0,30,F,C,Basic,Beta,C,-,cinza
12,13,28FC,Bverde,Basic,0,28,F,C,Basic,Comum,B,NaN,verde
13,14,26MC,A-Verde,Platinum,1,26,M,C,Platinum,Comum,A,-,verde
14,15,26MC,Croxo,Black-Alpha,1,26,M,C,Black,Alpha,C,NaN,roxo
15,16,27MC,B-Roxo,Platinum,1,27,M,C,Platinum,Comum,B,-,roxo
16,17,25FD,A-Verde,Black,1,25,F,D,Black,Comum,A,-,verde
17,18,28MD,C-Cinza,Black-Beta,0,28,M,D,Black,Beta,C,-,cinza
18,19,27MD,CAmarelo,Platinum-Alpha,1,27,M,D,Platinum,Alpha,C,NaN,amarelo
19,20,25FV,AAmarelo,Platinum,1,25,F,V,Platinum,Comum,A,NaN,amarelo

## Removendo os valores vazios

In [43]:
base.loc[base.Cliente.isna(), 'Cliente'] = 'Comum'

In [44]:
base

,ID,ChaveSituacao,ClassRisco,CatCliente,Pagamento,Idade,Sexo,EstadoCivil,Categoria,Cliente,Classe,Indicador,Risco
0,1,32FC,Ccinza,Basic-Alpha,1,32,F,C,Basic,Alpha,C,NaN,cinza
1,2,25MV,AAmarelo,Black,1,25,M,V,Black,Comum,A,NaN,amarelo
2,3,27MV,B-Amarelo,Basic-Beta,1,27,M,V,Basic,Beta,B,-,amarelo
3,4,26FD,BAmarelo,Black,0,26,F,D,Black,Comum,B,NaN,amarelo
4,5,26FD,C-Amarelo,Black,0,26,F,D,Black,Comum,C,-,amarelo
5,6,28FC,C-Amarelo,Platinum-Alpha,0,28,F,C,Platinum,Alpha,C,-,amarelo
6,7,27MD,A-Verde,Platinum-Beta,1,27,M,D,Platinum,Beta,A,-,verde
7,8,31MD,C-Cinza,Basic,0,31,M,D,Basic,Comum,C,-,cinza
8,9,28FS,A-Cinza,Black,1,28,F,S,Black,Comum,A,-,cinza
9,10,31MV,C+Amarelo,Platinum,1,31,M,V,Platinum,Comum,C,+,amarelo
10,11,29MV,AAmarelo,Basic,1,29,M,V,Basic,Comum,A,NaN,amarelo
11,12,30FC,C-Cinza,Basic-Beta,0,30,F,C,Basic,Beta,C,-,cinza
12,13,28FC,Bverde,Basic,0,28,F,C,Basic,Comum,B,NaN,verde
13,14,26MC,A-Verde,Platinum,1,26,M,C,Platinum,Comum,A,-,verde
14,15,26MC,Croxo,Black-Alpha,1,26,M,C,Black,Alpha,C,NaN,roxo
15,16,27MC,B-Roxo,Platinum,1,27,M,C,Platinum,Comum,B,-,roxo
16,17,25FD,A-Verde,Black,1,25,F,D,Black,Comum,A,-,verde
17,18,28MD,C-Cinza,Black-Beta,0,28,M,D,Black,Beta,C,-,cinza
18,19,27MD,CAmarelo,Platinum-Alpha,1,27,M,D,Platinum,Alpha,C,NaN,amarelo
19,20,25FV,AAmarelo,Platinum,1,25,F,V,Platinum,Comum,A,NaN,amarelo